# Generated by Django 4.0.4 on 2022-04-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_transacao_conta_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
