# Generated by Django 4.0.4 on 2022-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='conta_destino',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_origem',
            field=models.CharField(max_length=7),
        ),
    ]
