# Generated by Django 4.0.4 on 2022-04-21 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_transacao_conta_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacao', models.DateField()),
                ('data_importacao', models.DateField(default=datetime.datetime(2022, 4, 21, 13, 51, 23, 621395))),
            ],
        ),
    ]
