# Generated by Django 4.0.4 on 2022-04-21 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_alter_importacaorealizada_data_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaorealizada',
            name='data_importacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
