# Generated by Django 4.0.4 on 2022-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_transacao_agencia_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='conta_destino',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_origem',
            field=models.CharField(max_length=5),
        ),
    ]
