# Generated by Django 4.0.4 on 2022-04-21 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_importacaorealizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaorealizada',
            name='data_importacao',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 13, 51, 36, 295792)),
        ),
    ]
