# Generated by Django 4.0.4 on 2022-05-03 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controller', '0009_transacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='importacaorealizada',
            name='usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
