# Generated by Django 4.0.4 on 2022-05-07 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controller', '0010_remove_transacao_usuario_importacaorealizada_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaorealizada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
